import = ["~/.config/alacritty/themes/mellow.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

blur = true

decorations = "buttonless"
opacity = 0.5

[font]
normal.family = "GeistMono Nerd Font"
